name: Continuous Integration
concurrency:
  group: production

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        run: yarn install

      - name: Test the app
        run: yarn test

      - name: Install Cypress dependencies
        workdir: test/cypress
        run: yarn install

      - name: Run Cypress
        workdir: test/cypress
        run: yarn cypress:run
