name: Continuous Integration Chron

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set Node.js 26.x
        uses: actions/setup-node@v7
        with:
          node-version: 26.x

      - name: Enable corepack
        run: corepack enable

      - name: Run install
        run: yarn install

      - name: Install Cypress dependencies
        working-directory: tests/cypress
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run format check
        run: yarn format:check

      - name: Audit production dependencies
        run: yarn audit:prod

      - name: Audit dev dependencies
        run: yarn audit:dev
        continue-on-error: true

      - name: Run build
        run: yarn build

      - name: Test the app
        run: yarn test

      - name: Run Cypress
        working-directory: tests/cypress
        run: yarn cypress:run
