name: Publish To Chrome Store

on:
  release:
    types: [published]
    tags:
      - v.*.*.*

jobs:
  build:
    name: Build and Release to Chrome Extension Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run install
        run: yarn install

      - name: Install Cypress dependencies
        working-directory: tests/cypress
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Test the app
        run: yarn test

      - name: Run Cypress
        working-directory: tests/cypress
        run: yarn cypress:run

      - name: add chrome-webstore-cli
        working-directory: src/
        run: yarn add chrome-webstore-upload-cli@3

      - name: Submit to Chrome Extension Store
        working-directory: dist
        run: npx chrome-webstore-upload-cli@3 upload --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      